#!/bin/bash

TEMPLATE_FILE=$1
PAGES_DIR=$2
OUTPUT_DIR=$3

TEMPLATE=`cat $TEMPLATE_FILE`

for f in $PAGES_DIR/*
do
	TITLE=(`sed -n '2p' $f | tr ": " "\n"`)
	TITLE=${TITLE[1]}

	if [ $TITLE = "notitle" ]; then
		TITLE=""
	else
		TITLE=" | $TITLE"
	fi

	STYLE=(`sed -n '3p' $f | tr ": " "\n"`)
	STYLE=${STYLE[1]}

	if [ $STYLE = "nostyle" ]; then
		STYLE=""
	else
		STYLE="<link rel=\"stylesheet\" href=\"http://static.omsmith.ca/$STYLE\">"
	fi


	CONTENT=`tail -n +5 $f`

	TITLE_MATCH="{{PAGE_TITLE}}"
	STYLE_MATCH="{{STYLE_EXTRA}}"
	CONTENT_MATCH="{{PAGE_CONTENT}}"

	PAGE=${TEMPLATE/$TITLE_MATCH/$TITLE}
	PAGE=${PAGE/$STYLE_MATCH/$STYLE}
	PAGE=${PAGE/$CONTENT_MATCH/$CONTENT}

	OUTPUT_FILE=$OUTPUT_DIR/`basename $f`

	echo "$PAGE" > $OUTPUT_FILE
done
